### PR TITLE
Added content for the translation status section

### PR DESCRIPTION
**Pull request by andrey-helldar**
@Laravel-Lang/laravel-lang, hey!

I finally got the chance to do it 😅

See: https://laravel-lang.com/statuses/

### CODE REVIEW

**Comment by mohamedsabil83** [comment]
Nice 😄. Well done @andrey-helldar 👍🏽

**Comment by andrey-helldar** [comment]
@mohamedsabil83, thanks!)

**Comment by makowskid** [comment]
Great work @andrey-helldar !
thank a lot for all your contributions,
can we also add some kind of ignore section to not have situations like this?
https://laravel-lang.com/statuses/http-statuses/statuses/pl.html

**Comment by mohamedsabil83** [comment]
@makowskid, you can modify [this file](https://github.com/Laravel-Lang/lang/blob/main/locales/pl/_excludes.json) to ignore any key that you want to keep it as the original.

**Comment by andrey-helldar** [comment]
@makowskid, yes. @mohamedsabil83 wrote which file needs to be changed. The only thing is that it should be done in the [HTTP Statuses](https://github.com/Laravel-Lang/http-statuses/tree/main/locales/pl) project.

There you need to create a file similar to the one Mohamed [showed](https://github.com/Laravel-Lang/lang/blob/main/locales/pl/_excludes.json).

**Comment by andrey-helldar** [comment]
@makowskid, I've added exclusions: https://github.com/Laravel-Lang/http-statuses/pull/152

**Pull request merged**
